### ISSUE TITLE
Suggestions and bugs report

### ISSUE THREAD

**Issue by Pizzahut20** [justalemon/TuningShops#2]
Hello :)

I have a few suggestions and a few bugs to report after I used this script. If all of these things could be added/fixed, this mod would be perfect. Absolutely no pressure though, and everything else seems to work fine. Here it goes:

I do have to mention that a few options are missing, like the ability to choose different wheel types, wheel colors, 'custom tires', bulletproof tires, changing neon colors, window tint, metallic colors as a category (for metallic flakes in the paint), and interior/dials colors.

I've also noticed a few bugs: The repair vehicle option removed all my money, playing as Trevor, and by getting out and back into the said option, I can get all my money back. (https://imgur.com/dqeYn66)

This always shows up when choosing the 'neon layout' option, and when choosing the 'dials' option (tested with Sultan RS): https://imgur.com/TjI8RcF https://imgur.com/3inohAK

On some (Arena War) vehicles the camera either looks at nothing (like a very close-up of the vehicle interior of the Scarab) or doesn't do anything, and gives the same errors as the ones pictured above. ^ https://imgur.com/O6XmxHl https://imgur.com/hhwsK8x https://imgur.com/YCXktV6 https://imgur.com/KMKhlBr.

Lastly, if possible, can you make it so various things like the hood, doors, and/or trunk open when you select certain options? At least for the options like: Air Filter, Doors, Engine Block, Struts, and probably some more that I've forgotten.

Again, absolutely no pressure, you do what you want to do with all... this. Thanks :)

**Comment by justalemon** [comment]
Hi! I like to keep GitHub issues organized, so I created issues #3, #4, #5 and #6 to keep track of each individual bug report and feature request.

Thanks for contributing!
